# Login
# @name login
POST http://localhost:8000/login/
Content-Type: application/json

{
	"username": "parracho@gmail.com",
	"password": "12345"
}
###

@auth = {{login.response.body.access_token}}

GET http://localhost:8000/parties
Authorization: 'Bearer {{auth}}'